---
firewall_allowed_tcp_ports:
  - "22"
  - "80"
haproxy_backend_servers:
  - name: app1
    address: 10.164.210.121:80
  - name: app2
    address: 10.164.210.122:80
haproxy_backend_balance_method: 'leastconn'